### PR TITLE
Disambiguate as_ref() to fix build under Rust 1.36

### LINKED ISSUE #222: gu-base no longer builds on Rust 1.36+
```
   Compiling gu-actix v0.1.0 (https://github.com/golemfactory/golem-unlimited?branch=feature/gu-client-rpc#36cb510e)
   Compiling gu-base v0.1.0 (https://github.com/golemfactory/golem-unlimited?branch=feature/gu-client-rpc#36cb510e)
   Compiling gu-net v0.1.0 (https://github.com/golemfactory/golem-unlimited?branch=feature/gu-client-rpc#36cb510e)
error[E0283]: type annotations required: cannot resolve `std::string::String: std::convert::AsRef<_>`
   --> /home/marcin/.cargo/git/checkouts/golem-unlimited-8aa5a0012b75d98f/36cb510/gu-base/src/output.rs:114:30
    |
114 |             let prg = self.0.as_ref();
    |                              ^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0283`.
error: Could not compile `gu-base`.
warning: build failed, waiting for other jobs to finish...
error: build failed
marcin@archtop /home/marcin/proj/golem/gumpi [101] (guclient|✚1)
[10:44:28] $ rustup run nightly cargo --version
cargo 1.37.0-nightly (545f35425 2019-05-23)
```
This also happens on beta:
```
cargo 1.36.0-beta (c4fcfb725 2019-05-15)
```

### PR DESCRIPTION
**Pull request by marmistrz**
Closes #222

### CODE REVIEW

**Review by tworec — APPROVED** [review]
lgtm
